---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Include UFW setup
  import_tasks: ufw.yml

- name: Include SSH hardening
  import_tasks: ssh.yml

- name: Include Fail2Ban setup
  import_tasks: fail2ban.yml

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the server if required
  reboot:
    msg: "Reboot initiated by Ansible after package updates"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 10
    test_command: uptime
  when: reboot_required.stat.exists

- name: Remove reboot-required flag after reboot
  file:
    path: /var/run/reboot-required
    state: absent
  when: reboot_required.stat.exists

