---
- name: Create server with attached firewall and IPs
  hetzner.hcloud.server:
    name: "{{ server_name }}"
    server_type: "{{ server_type }}"
    image: "{{ image }}"
    location: "{{ location }}"
    ssh_keys:
      - "{{ ssh_key_name }}"
    firewalls:
      - default
    ipv4: ipv4
    ipv6: ipv6
    labels:
      role: "webmail"
    state: present
  register: hcloud_server
